version: "3.9"

services:
    kbot2:
        build: "./"
        restart: always
        env_file:
            - ./.env.production
        environment:
            - MONGODB_PORT=${DOCKER_MONGODB_PORT}
            - MONGODB_HOST=mongodb
            - MONGODB_USER=${DOCKER_MOGNODB_USERNAME}
            - MONGODB_PASSWD=${DOCKER_MOGNODB_PASSWORD}
        ports:
            - 22000:80
        volumes:
            - ./mount/files:/mount/
            - ./mount/users:/build/images/user/
        external_links:
            - mongodb:mongodb
        networks:
            - databases_default

networks:
    databases_default:
        external: true
