version: "3.9"

services:
    kbot2:
        depends_on:
            - mongodb-kbot2
        build: "./"
        restart: always
        env_file:
            - .env.local
        environment:
            - MONGODB_PORT=27017
            - MONGODB_HOST=mongodb-sbs
            - MONGODB_USER=sbs
            - MONGODB_PASSWD=sbs
            - MONGODB_DATABASE=sbs
        ports:
            - "${DOCKER_PORT}:80"
        volumes:
            # config for the cashboard if you want to edit that copy to a other path and mount it to here.
            - ./mount/files:/mount/
            - ./mount/users:/build/images/user/
        networks:
            - sbs-network

    mongodb-kbot2:
        # user: "${DOCKER_UID}:${DOCKER_GID}"
        image: mongo
        volumes:
            - './mount/mongodb:/data/db'
        environment:
            MONGO_INITDB_DATABASE: sbs
            MONGO_INITDB_ROOT_USERNAME: sbs
            MONGO_INITDB_ROOT_PASSWORD: sbs
        networks:
            - sbs-network

networks:
    sbs-network:
