name: 🔨 Build and Deploy

on: [ push, pull_request ]

jobs:
  test-docker:
    name: 🔨 Build as Docker
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
      - name: ⚡ Build as docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: user/app:latest

  test-app:
    name: 🔨 Test and Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x, 19.x, 20.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
      - name: 🔧 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: ✨ Install packages
        run: yarn install
      - name: ⚡ Build App
        run: yarn build

  deploy:
    needs: [ test-app, test-docker ]
    name: 🚀 Deploy to Server
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Execute update script on server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: ~/docker/github.sh "${{ github.event.repository.name }}" "${{ github.head_ref || github.ref_name }}"